### PR TITLE
Bugfix/sync app cat

### LINKED ISSUE #164: Synchronize Application Categories lookup table from SHAID
[Delete any non-applicable sections, but we may ask for more information.]

### Bug Report
The App Category Lookup table is currently hard-coded and not kept in sync using the respective SHAID API endpoint. Recommend updating the table to add the `name` column (to align with SHAID's structure) and add logic to periodically pull and upsert category data from SHAID.

##### Reproduction Steps
1.  Add a new category to SHAID.
2. The sdl server will not update on startup.

##### Expected Behavior
Whenever the shaid server is updated, the sdl server should be checking against it on startup or daily through cron jobs.

##### Observed Behavior
The categories are not updated.

##### OS, Browser & Version Information
NA

##### Test Case, Sample Code, and / or Example App
NA

### PR DESCRIPTION
**Pull request by russjohnson09**
Fixes #164 

This PR is **ready** for review.

### Risk
This PR makes **no** API changes.

### Testing Plan
After running the migration there are still a few categories that exist on shaid and not on the sdl server. After starting the sdl server confirm that these new categories were inserted into (eg Remote Control).

### Summary
Adds a new column to categories name and synchronizes the categories table from shaid on startup or as a part of the daily cron job.

##### Breaking Changes
None.

##### Enhancements
Categories are updated automatically.

##### Bug Fixes
Categories should have already been updated automatically similar to how applications are pulled in from shaid.

### Tasks Remaining:
No tasks remaining.

### CLA
- [x] I have signed [the CLA](https://docs.google.com/forms/d/e/1FAIpQLSdsgJY33VByaX482zHzi-xUm49JNnmuJOyAM6uegPQ2LXYVfA/viewform)

### CODE REVIEW

File: app/v1/applications/sql.js [hunk 1]
```diff
@@ -245,8 +245,19 @@ function getAppPermissionsId (id) {
...
+            {
+                'name': name
+            }
+        )
+        .toString();
+}
+
 function getAppCategory (id) {
-    return sql.select('categories.id', 'display_name')
+    return sql.select('categories.id','display_name')
```
Comment (nickschwab) [inline app/v1/applications/sql.js]: Unnecessary deletion.

```suggestion
    return sql.select('categories.id', 'display_name')
```

File: app/v1/applications/sql.js [hunk 2]
```diff
@@ -539,6 +550,18 @@ function insertAppServicePermission (obj) {
...
+    let insertObj = {
+        id: obj.id,
+        name: obj.name,
+        display_name: obj.display_name
+    };
+
+    return sql.insert('categories', insertObj)
+        .returning('*')
+        .toString();
+}
```
Comment (nickschwab) [inline app/v1/applications/sql.js]: Use bulk upsert statement to insert-or-update automatically. See app/v1/services/sql.js for example.
