### PR TITLE
Include Navbar functionality in Header on thinner screens

### LINKED ISSUE #248: Navbar-toggler has no functionality
### Bug Report
There is a button in the Policy Server Header that only appears in smaller browser screens. The button has no functionality. The properties of the button suggest that it was mean to be attached to navbar for smaller browsers.

##### Reproduction Steps
1. Open a browser window to any page in the Policy Server UI.
2. Resize the window width until the sidebar disappears. There will now be a hamburger button in the header's top-right corner.
3. Click the hamburger button.

##### Expected Behavior
Since the sidebar disappears, it's implied that the new button should open a replacement nav menu.

##### Observed Behavior
Nothing happens when the button is clicked because there is no functionality attached to the button.

##### OS, Browser & Version Information
* Browser: Chrome, Firefox, Safari
* Policy Server Version: 2.11

### PR DESCRIPTION
**Pull request by renonick87**
Fixes #248 

This PR is **ready** for review.

### Risk
This PR makes **no** API changes.

### Testing Plan
This PR was tested in Chrome, Firefox, Safari, and Safari on mobile. NOTE: Having basic authentication enabled adjusts the formatting of the header since a separate new button will be visible, so this PR was tested both with and without basic authentication enabled.

### Summary
This PR updates the functionality of the hamburger button in the Header that appears on smaller screens, usually when the sidebar is not visible. It will now open a dropdown nav similar to the sidebar nav. If the screen is resized to be large enough (the threshold is about 768px wide) both the button and the nav will disappear and the side bar will reappear. The sidebar and dropdown do not appear at the same time, so the CSS for both and other additional pages needed to be updated so the formatting wouldn't break on certain screen sizes.

### CLA
- [X] I have signed [the CLA](https://docs.google.com/forms/d/e/1FAIpQLSdsgJY33VByaX482zHzi-xUm49JNnmuJOyAM6uegPQ2LXYVfA/viewform)

### CODE REVIEW

File: src/components/common/Header.vue [hunk 1]
```diff
@@ -3,21 +3,39 @@
...
         </button>
 
-        <div class="collapse navbar-collapse" id="navbarsExampleDefault">
-            <ul class="navbar-nav mr-auto">
-                <!--
-                <li class="nav-item active">
-                    <a class="nav-link" href="#">Applications/</a>
-                </li>
-                -->
+        <div class="navbar-collapse d-lg-none d-xl-block" data-toggle="collapse" v-if="!isHidden && (innerWidth < 768)" id="navbarsExampleDefault">
```
Comment (crokita) [inline src/components/common/Header.vue:13]: Is the innerWidth if condition needed here? I removed only that expression in the if statement and seemed to get the same behavior on my browsers. Does something undesirable happen when it's removed?

Comment (renonick87) [reply src/components/common/Header.vue:13]: The innerWidth check is there to handle a specific case where basic authentication is enabled, and so the user login icon displays in the header alongside the burger button.
Start by having a small browser window, open the navbar from the burger button but don't close the navbar, then resize the window to be larger so that the navbar disappears. You'll see that even though the navbar is not visible, the user icon is forced to the left side of the screen, sometimes overlapping with the SDL logo. This happens because the CSS is saying that the div should not be visible in a larger screen, but the `v-if` condition is stating that the div should still be present, so you get an invisible div messing with the formatting.
Screen Shot 2021-06-24 at 10 15 44 AM

**Review by crokita — APPROVED** [review]

**Comment by renonick87** [comment]
Fixed an issue where if basic authentication is enabled, then upon loading the login page the UI would attempt to update the pending application count but would fail because the request is unauthorized since the user has not logged in yet. This failed request would redirect the user to the applications page, which would redirect to the login page, and the page would be stuck in an infinite loop.
To fix this, these specific failed requests will no longer redirect to another page, and the pending application count will be updated after the user has logged in.
This PR is again ready for review.

**Review by crokita — APPROVED** [review]
